micronaut:
  application:
    name: oms-driver
temporal:
  server:
    address: 127.0.0.1:7233
#datasources:
#  default:
#    url: jdbc:postgresql://localhost:5432/postgres
#    driverClassName: org.postgresql.Driver
#    username: postgres
#    password: postgres
#    schema-generate: CREATE_DROP
#    dialect: POSTGRES